#! /usr/bin/env node

var r4ffi=require("../lib/r4ffi");

r4ffi.init()
r4ffi.eval("a=rnorm(10)")
console.log(r4ffi.get_ary("a"))
console.log(r4ffi.get_ary("as.integer(1:3)"))
console.log(r4ffi.get_ary("c('titi','tutu2')"))
console.log(r4ffi.get_ary("c(TRUE,FALSE,TRUE)"))
r4ffi.set_ary("a",[1,3,2])
r4ffi.eval("a")
r4ffi.set_ary("a",[1.1,3.2,2.3])
r4ffi.eval("a")
r4ffi.set_ary("a",[true,false,true])
r4ffi.eval("a")
r4ffi.set_ary("a",["tutu","toto2"])
r4ffi.eval("a")
